In [1]:
#Dependencies
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import os

In [2]:
##Sets Pandas to truncate dataframes
pd.set_option("display.max_rows", 10)

In [4]:
##Sets Pandas to not truncate dataframes
pd.set_option("display.max_rows", None, "display.max_columns", None)

In [6]:
#Input Paths
colordata = 'dataformodel/colorvisibility.csv'
cleaneddata = 'Output/deepcleanedmini.csv'

In [8]:
#Read In CSV
color_df = pd.read_csv(colordata)
color_df

       Color  Visibility  Tickets
0      Black         1.0    98291
1      Brown         2.0    15744
2   Burgundy         3.0     1161
3       Blue         4.0     9836
4        Red         9.0    19419
..       ...         ...      ...
10      Pink         8.5        2
11     White         7.0   112729
12     Other         5.0     3204
13     Light         7.5      334
14      Dark         2.5      447

[15 rows x 3 columns]

In [9]:
df = pd.read_csv(cleaneddata)

In [10]:
df

,Summons Number,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Street Code1,Street Code2,Street Code3,Violation Location,Violation Precinct,Violation Time,Issuer Precinct,House Number,Street Name,Intersecting Street,Vehicle Color,Vehicle Year
0,1478409990,01/01/2021,51,SUBN,CHEVR,70620,11980,0,46.0,46,1027A,2,2001,UNIVERSITY AVE,AQUEDUCT WALK,BLK,2008
1,1478421186,01/01/2021,20,SDN,KIA,36230,26610,0,26.0,26,0103P,1,425,WEST 123RD STREET,MORNINGSIDE PARK,GREY,2016
2,8556047440,01/01/2021,50,SUBN,HONDA,0,0,0,115.0,115,0440P,115,N,35th Ave,0ft E/of 71st St,BK,2008
3,8556047464,01/01/2021,71,SUBN,FORD,7990,0,0,115.0,115,0547P,115,S,31st Ave,20ft W/of 85th St,BK,2016
4,8786592798,01/01/2021,71,4DSD,NISSA,58730,0,0,90.0,90,1131A,90,N,Marcy Ave,30ft E/of Division A,BK,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368037,8994356642,03/31/2021,19,4DSD,BMW,76430,0,0,75.0,75,0306P,75,E,Sheffield Ave,40ft S/of Fulton St,GREY,0
368038,8994356733,03/31/2021,50,4DSD,CHEVR,0,0,0,75.0,75,0345P,75,E,Van Siclen Ave,0ft N/of Jamaica Ave,OTHER,0
368039,8994356770,03/31/2021,71,SUBN,FORD,53210,0,0,75.0,75,0405P,75,E,Jerome Ave,4ft S/of Arlington A,BK,2018
368040,8995200509,03/31/2021,14,UTIL,HIN,93060,0,0,88.0,88,0830A,88,N,Williamsburg St West,10ft W/of Steuben St,WH,2019
368041,8995200534,03/31/2021,71,TOW,INTER,0,0,0,88.0,88,0846A,88,N,Emerson Pl,120ft E/of Classon A,RD,2004